# Step 1 (alpine is linux distribution)...
FROM alpine

# Step 2 (installing binutils program inner this OS)..
RUN apk add binutils

# Step 3 (configure the Software).

# Step 4 (set default commands)
